const SAVE_PROJECT_ERROR = "SAVE_PROJECT_ERROR";
const SAVE_PROJECT_SUCCESS = "SAVE_PROJECT_SUCCESS";
const SAVE_PROJECT_TRIGGER = "SAVE_PROJECT_TRIGGER";

const DELETE_PROJECT_ERROR = "DELETE_PROJECT_ERROR";
const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
const DELETE_PROJECT_TRIGGER = "DELETE_PROJECT_TRIGGER";

const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";
const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
const GET_PROJECTS_TRIGGER = "GET_PROJECTS_TRIGGER";

export {
  SAVE_PROJECT_ERROR,
  SAVE_PROJECT_SUCCESS,
  SAVE_PROJECT_TRIGGER,
  DELETE_PROJECT_ERROR,
  DELETE_PROJECT_SUCCESS,
  DELETE_PROJECT_TRIGGER,
  GET_PROJECTS_ERROR,
  GET_PROJECTS_SUCCESS,
  GET_PROJECTS_TRIGGER,
};
