const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";
const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
const GOOGLE_LOGIN_TRIGGER = "GOOGLE_LOGIN_TRIGGER";
const GOOGLE_LOGIN_CONFIRM_REDIRECT = "GOOGLE_LOGIN_CONFIRM_REDIRECT";
const GOOGLE_LOGIN_VERIFY_CODE = "GOOGLE_LOGIN_VERIFY_CODE";

export {
  GOOGLE_LOGIN_ERROR,
  GOOGLE_LOGIN_SUCCESS,
  GOOGLE_LOGIN_TRIGGER,
  GOOGLE_LOGIN_CONFIRM_REDIRECT,
  GOOGLE_LOGIN_VERIFY_CODE,
};
